### ISSUE TITLE
Paths provided by nova-eslint not working with typescript-eslint/parser

### ISSUE THREAD

**Issue by sgwilym** [apexskier/nova-eslint-forked#56]
Came upon this when editing a file within a TS project that is using `@typescript-eslint/eslint-plugin`: 

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: ../../../../Volumes/Macintosh HD/Users/gwil/Projects/App/src/SomeComponent.tsx.
The file must be included in at least one of the projects provided.
```

I tried to solve this for a while with our own configuration: editing the `include` option of tsconfig.json, and messing with all kinds of settings related to root directories, all with no luck. 

But after doing some logging from this extension, I think it may have something to do with the way the paths for the files to be linted are being parsed.

To test this idea, I started manually editing the arguments passed [on this line](https://github.com/apexskier/nova-eslint/blob/master/src/process.ts#L84).

After removing the prefix of `/Volumes/Macintosh HD` from `cleanFilePath` and `workspacePath`, linting worked as expected.

If I do the inverse (append `/Volumes/Macintosh HD` to `eslint`), linting does *not* work.

## Unmodified nova-eslint (❌ not working)

Variable | Value
-------- | ------
`cleanFilePath` | `/Volumes/Macintosh HD/Users/gwil/Projects/App/src/SomeComponent.tsx`
`workspacePath` | `/Volumes/Macintosh HD/Users/gwil/Projects/App`
`eslint` | `/Users/gwil/Projects/StadiumGoods-App/node_modules/.bin/eslint`

## Modified `cleanFilePath` and `workspacePath` nova-eslint (✅ working) 

Variable | Value
-------- | ------
`cleanFilePath` | `/Users/gwil/Projects/App/src/SomeComponent.tsx`
`workspacePath` | `/Users/gwil/Projects/App`
`eslint` | `/Users/gwil/Projects/StadiumGoods-App/node_modules/.bin/eslint`

## Modified `eslint` nova-eslint (❌ not working)

Variable | Value
-------- | ------
`cleanFilePath` | `/Volumes/Macintosh HD/Users/gwil/Projects/App/src/SomeComponent.tsx`
`workspacePath` | `/Volumes/Macintosh HD/Users/gwil/Projects/App`
`eslint` | `/Volumes/Macintosh HD/Users/gwil/Projects/StadiumGoods-App/node_modules/.bin/eslint`

**To reproduce**

I'm wondering how to produce this because a new CRA app using Typescript (which uses `@typescript-eslint` internally) does not have this problem. I believe this is because it does not use the parser's `project` setting which connects it to a tsconfig, something which only a few of typescript-eslint rule's require.

**Environment**

- Nova version: 213794
- Extension version: 1.2.1
- ESLint version: v7.11.0
- macOS version: 10.15.7
- NodeJS information:
  - node version: v14.4.0
  - npm version: 6.14.4
  - installation method: homebrew

**Comment by apexskier** [comment]
Resolved by bedc13d6a120b3420840c67832c619b1ac82f043

**Comment by apexskier** [comment]
Included in release [v1.3.0](https://github.com/apexskier/nova-eslint/releases/tag/v1.3.0)

**Comment by destegabry** [comment]
Thank you @apexskier, this really makes Nova one step closer to replace VSCode in my typescript/react toolchain! 

I have enabled the "fix on save" option, I get the obvious errors fixed but Nova remains behind on it. For example, I deliberately removed a semicolon, saved and got the file auto fixed from ESLint… but Nova still shows the error:

<img width="297" alt="Schermata 2020-10-29 alle 09 44 46" src="https://user-images.githubusercontent.com/4654358/97545634-955eb700-19cb-11eb-8e68-ef4f68b85b31.png">

Is it possible to enable some sort of debounced-validate-as-you-type behavior?

I don't know if this is in the scope of this plugin, but here's another "problem": VSCode fix errors like the following one using the "Quick fix…" contextual menu:

<img width="922" alt="Schermata 2020-10-29 alle 09 47 27" src="https://user-images.githubusercontent.com/4654358/97546022-233aa200-19cc-11eb-8c4e-012a522e3796.png">

Do you think is possible to enable a similar feature? The proposed "Quick actions" aren't very useful:

<img width="443" alt="Schermata 2020-10-29 alle 09 58 56" src="https://user-images.githubusercontent.com/4654358/97546982-7d883280-19cd-11eb-927a-78049d026c54.png">

**Comment by apexskier** [comment]
@destegabry Thanks for the feedback, but those look unrelated to this issue with the typescript-eslint/parser. Can you please open a new issue so we can ensure the conversation is easier to follow and discover for other people?

**Comment by destegabry** [comment]
Yep, will do it right now
